#!/bin/sh

# cat temp.wan | awk '

CE=2403:9200:fffe::65
RULE6P=2403:9200:fffe:fff4::/62

ssh root@$CE "/usr/sbin/tcpdump -ttSni eth0 src net $RULE6P"  | awk '
  BEGIN {
        secondago = 0;
        fr = 0;  
	now = systime(); timediff = 0; 
  }
  $10 ~ /Flags/ {
	if (timediff == 0) timediff = now - $1; 
        tm = $1 + timediff; 
	src = $7; dst = $9; 
        match(src, /([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)/, a); 
        sa = a[1]; sp = a[2];
        match(dst, /([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)/, a); 
        da = a[1]; dp = a[2];
        match($11, /\[([.SFPR ]+)\]/, a);
        fl = a[1];
	printf("%9.6f ", tm); 
        print sa, sp, da, dp, fl;

	if ((fl ~ /S/) && ((src, dst) in s)) {
		fr++;
	}

	s[src, dst] = tm; 

        if (fl ~ /F/) {
		delete s[src, dst];
	}

        if (tm - secondago > 1) {
		for (srcdst in s) {
			split(srcdst, b, SUBSEP);
			ssrc = b[1]; sdst = b[2]; 
			match(ssrc, /([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)/, a); 
			ssa = a[1]; ssp = a[2];
			match(sdst, /([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)/, a); 
			sda = a[1]; sdp = a[2];
			if (tm - s[ssrc, sdst] > 600) {
 				delete s[srcdst]; 
				w[ssp]--; if (w[ssp] == 0) delete w[ssp]; 
				v[sda]--; if (v[sda] == 0) delete v[sda]; 
                	} else {
				w[ssp] = (ssp in w)?(w[ssp] + 1):1; 
				v[sda] = (sda in v)?(v[sda] + 1):1; 
			}
		}
		out = strftime("%Y%m%d") ".wan.bysec" ;
		printf("%9.6f ", tm) >> out; 
                print length(w), length(v), length(s), fr >> out; fflush(out);
                secondago = tm; fr = 0;
		delete w; delete v;
        } 
  }
  END {
        for (s in ss) {
                print s, ss[s]; 
        }
        print length(ss);
  }'

